### Create customer
POST http://localhost:8080/customer
Content-Type: application/json

### Get all customers
GET http://localhost:8080/customer/all
Content-Type: application/json

### Get customer by id
GET http://localhost:8080/customer/1
Content-Type: application/json

### Credit balance
POST http://localhost:8080/customer/1/credit?amount=1000000000
Content-Type: application/json

### Debit balance
POST http://localhost:8080/customer/1/debit?amount=80
Content-Type: application/json

