CREATE TABLE IF NOT EXISTS orders
(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId INT NOT NULL,
    state TEXT NOT NULL,
    products JSONB NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT now(),
    updatedAt TIMESTAMP NOT NULL DEFAULT now()
);
