CREATE TABLE IF NOT EXISTS customers
(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    balance INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);
