### Get all orders for user
GET http://localhost:8082/order/all?userId=1
Content-Type: application/json

### Get order by id
GET http://localhost:8082/order/1
Content-Type: application/json

### Create order
POST http://localhost:8082/order?userId=1
Content-Type: application/json
